### ISSUE TITLE
Inquiry about blackip ip ver6

### ISSUE THREAD

**Issue by SSJune821** [maravento/blackip#2]
Hello. 
I would like to inquire about the blackip project.
I think blackip is a list about ip version 4, but will there be blackip for ip version 6?

**Comment by maravento** [comment]
hi. Thank you for your visit and interest in this project.
At the moment only IPv4, since there are not enough public block lists on the internet to be able to unify an IPv6 block list.
Remember that blackip is not a list of its own, created by us, but a script that collects different public block lists, and then unifies and purges them, to create a single resulting block list. Regards
