### ISSUE TITLE
Is it discontinued?

### ISSUE THREAD

**Issue by LufoX11** [maravento/blackip#4]
Hi! First of all, GREAT work! I'm using it in my webservers to update ModSec banned IPs.

Since there were no more updates from november, I'd like to know if you are planning to continue this project or the list won't be updated anymore.

Thanks!

**Comment by maravento** [comment]
Thank you for using our project.
[Blackip has just been updated](https://github.com/maravento/blackip/commit/86619b8ca34554ba49c00ce7acc9f993b96983f2). The update average is maximum 2 months. The cause is that debugging takes time and hardware resources and we are limited.
However, if you want to increase the update frequency, you can do it yourself by downloading the bash update script and following the instructions. Check [Update chapter](https://github.com/maravento/blackip#update)

**Comment by LufoX11** [comment]
Thanks!

**Comment by HydraDragonAntivirus** [comment]
Please open discussions. Also  it always going to be updated.

**Comment by maravento** [comment]
The question was answered correctly. That's why the issue was closed.
The blackip update happens approximately every month (depending on my availability). And if any user doesn't want to wait, they can download the update script (bipupdate.sh) and run it on their own.
If you have any issue, you can open another
