### ISSUE TITLE
Feuture request open discussion

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [maravento/blackip#6]
This so great project but it would be more great if we can talk about non issue things

**Comment by maravento** [comment]
Due to scheduling problems, I can only attend to issues for open source projects

Thank you for contacting to [Maravento Studio](https://www.maravento.com/)

- If your problem is related to some of our projects in [github](https://github.com/maravento), subscribe to the project and create an "issues" in the repository of your interest
- If your problem is related to any of our posts published on the blog, register on [disqus](https://disqus.com/) and describe your problem at the end of the post of your interest.
- If your interest is advertising on our blog, let us know to contact@maravento.com to send you rates
- If your interest is to publish on our blog, this option is not available
- For business support, send your request to contact@maravento.com

regards
