### ISSUE TITLE
CIDR (nethash)

### ISSUE THREAD

**Issue by ben-auo** [maravento/blackip#7]
> blackip.txt is a list IPv4. Does not include CIDR

Cool project! Any reason you don't support CIDR with nethash?

**Comment by maravento** [comment]
Hi, thanks for using BlackIp

[Important about BlackIP](https://github.com/maravento/blackip#important-about-blackip)

- blackip.txt is a list IPv4. Does not include CIDR

The reason is that since BlackIP verifies each IP address before listing it, to verify a CIDR it is necessary to break it down to verify each IP, and this is very resource intensive, and we do not have these resources and time to process CIDR.
If you check the `bipupdate.sh` update script, there is the commented out CIDR processing part:

https://github.com/maravento/blackip/blob/master/bipupdate/bipupdate.sh

```
   # CIDR2IP (High consumption of system resources)
    #function cidr() {
    #       $wgetd "$1" -O - | sed '/^$/d; /*#/d' | uniq > cidr.txt && sort -o cidr.txt -u cidr.txt >/dev/null 2>&1
    #       python tools/cidr2ip.py cidr.txt >> bip
    #}
    #       cidr 'https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset'
    #       cidr 'https://www.stopforumspam.com/downloads/toxic_ip_cidr.txt'

```
And this is the python script in charge of processing the CIDRs, in case you want to try it:

https://github.com/maravento/blackip/blob/master/bipupdate/tools/cidr2ip.py

However, you can add your own CIDRs, as explained in [Advanced Rules](https://github.com/maravento/blackip#about-squid-rule)

https://github.com/maravento/blackip/blob/master/bipupdate/lst/blackcidr.txt

```
# Block Rule for IP/CIDR ACL (not included in blackip.txt)
acl blackcidr dst "/path_to/blackcidr.txt"
http_access deny blackcidr
```

PD: We are not familiar with the term "CIDR with nethash". Both terms are different and unrelated to each other.
If you want to block IP addresses, this project may be useful for you.
If you want to block miners, there are other more specific projects dedicated to stopping mining, although you can use "Zero Trust" techniques that are explained in [Advanced Rules](https://github.com/maravento/blackip#about-squid-rule)

```
## Zero Trust Rule (ZTR)
acl no_ip url_regex -i [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}
http_access deny no_ip
```

Thanks for your visit
